### ISSUE TITLE
3.18 issue with Cybersource blank screen on event registration instead of 'thank you' page. Not a problem in 3.17

### ISSUE THREAD

**Issue by Stoob** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#239]
Had an interesting issue where payments using Cybersource were going through, yet the registration 'thank you' for events  never showed up.  Instead the blank screen with IPN was all we say (see below) Rolled back to 3.17 and the problem went away.

![Blank Registration Screen](https://user-images.githubusercontent.com/1683473/203616328-bcd53e34-a3cb-424d-812d-90fc16a87ee8.png)

Found this error in the logs.  

> 3825DB Constrai...

```
Nov 21 18:19:54  [error] ipn_payment_callback_exception
Array
(
    [context] => Array
        (
            [backtrace] => #0 /home/milstein/www/www/sites/default/files/civicrm/extensions/nz.co.fuzion.omnipaymultiprocessor/CRM/Core/Payment/OmnipayMultiProcessor.php(832): CRM_Core_Payment_PaymentExtended->handleError('error', 'ipn_completion ...', '3825DB Constrai...', 9000, 'An error may ha...')
#1 /home/milstein/www/www/sites/default/files/civicrm/extensions/nz.co.fuzion.omnipaymultiprocessor/CRM/Core/Payment/OmnipayMultiProcessor.php(766): CRM_Core_Payment_OmnipayMultiProcessor->processPaymentNotification(Array)
#2 /home/milstein/www/www/sites/all/modules/civicrm/CRM/Core/Payment.php(1647): CRM_Core_Payment_OmnipayMultiProcessor->handlePaymentNotification()
#3 /home/milstein/www/www/sites/all/modules/civicrm/CRM/Core/Payment.php(1540): CRM_Core_Payment::handlePaymentMethod('handlePaymentNo...', Array)
#4 /home/milstein/www/www/sites/all/modules/civicrm/CRM/Core/Invoke.php(285): CRM_Core_Payment::handleIPN()
#5 /home/milstein/www/www/sites/all/modules/civicrm/CRM/Core/Invoke.php(69): CRM_Core_Invoke::runItem(Array)
#6 /home/milstein/www/www/sites/all/modules/civicrm/CRM/Core/Invoke.php(36): CRM_Core_Invoke::_invoke(Array)
#7 /home/milstein/www/www/sites/all/modules/civicrm/drupal/civicrm.module(471): CRM_Core_Invoke::invoke(Array)
#8 /home/milstein/www/www/includes/menu.inc(527): civicrm_invoke('payment', 'ipn')
#9 /home/milstein/www/www/index.php(21): menu_execute_active_handler()
#10 {main}
            [message] => An error may have occurred. Please check your receipt is correct
        )

)
```

**Comment by eileenmcnaughton** [comment]
That's frustrating because the error message is truncated :-(

**Comment by Stoob** [comment]
One could say that about almost all Civi error messages, couldn't one? ;-)

**Comment by eileenmcnaughton** [comment]
You might get more info replaying the notification through the api - although I suspect you probably just want to sit on the rolled back version for a bit

**Comment by Stoob** [comment]
Yep we're doing version 3.17 just fine.
