### ISSUE TITLE
Error when Paypal Checkout payment is processed

### ISSUE THREAD

**Issue by nickperkins** [eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#249]
'm setting up a membership form using a contribution page. I'm using the Paypal Checkout payment provider. When I complete the process and I'm returned to the site, I get a critical error page.

The php error logs show the following error:

```[25-Aug-2023 19:51:19 Australia/Brisbane] PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #2 must be of type array, null given in /home/xxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Contribute/Form/Contribution/Confirm.php:294
Stack trace:
#0 /home/xxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Contribute/Form/Contribution/Confirm.php(294): array_merge(Array, NULL)
#1 /home/xxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Contribute/Form/Contribution/Main.php(1345): CRM_Contribute_Form_Contribution_Confirm->preProcess()
#2 /home/xxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Contribute/Form/Contribution/Main.php(1102): CRM_Contribute_Form_Contribution_Main->skipToThankYouPage()
#3 /home/xxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php(617): CRM_Contribute_Form_Contribution_Main->postProcess()
#4 /home/xxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Upload.php(153): CRM_Core_Form->mainProcess()
#5 /home/xxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Upload.php(120): CRM_Core_QuickForm_Action_Upload->realPerform(Object(CRM_Contribute_Form_Contribution_Main), 'upload')
#6 /home/xxx/public_html/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Upload->perform(Object(CRM_Contribute_Form_Contribution_Main), 'upload')
#7 /home/xxx/public_html/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Contribute_Form_Contribution_Main), 'upload')
#8 /home/xxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php(355): HTML_QuickForm_Page->handle('upload')
#9 /home/xxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(319): CRM_Core_Controller->run(Array, NULL)
#10 /home/xxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(69): CRM_Core_Invoke::runItem(Array)
#11 /home/xxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(36): CRM_Core_Invoke::_invoke(Array)
#12 /home/xxx/public_html/wp-content/plugins/civicrm/civicrm.php(1199): CRM_Core_Invoke::invoke(Array)
#13 /home/xxx/public_html/wp-content/plugins/civicrm/includes/civicrm.basepage.php(380): CiviCRM_For_WordPress->invoke()
#14 /home/xxx/public_html/wp-includes/class-wp-hook.php(310): CiviCRM_For_WordPress_Basepage->basepage_handler(Object(WP))
#15 /home/xxx/public_html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#16 /home/xxx/public_html/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#17 /home/xxx/public_html/wp-includes/class-wp.php(796): do_action_ref_array('wp', Array)
#18 /home/xxx/public_html/wp-includes/functions.php(1335): WP->main('')
#19 /home/xxx/public_html/wp-blog-header.php(16): wp()
#20 /home/xxx/public_html/index.php(17): require('/home/xxx/pub...')
#21 {main}
  thrown in /home/xxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Contribute/Form/Contribution/Confirm.php on line 294```

This is the first time I've tried to set up civicrm, so I'm a little lost on this one. Could this be related to running on php 8.1?

**Comment by Patel-Amar** [comment]
I'm having a similar issue except on line 547. I believe it is because omnipay is not sending out the preapprovalparameters as a part of the object key. I am using paypal checkout - have yet to find a solution
